build:
  image: ghcr.io/algebraic-programming/taskr/buildenv:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
  - docker
  - x86
  - infiniband 
  script:
  - export HOME=/home/hicr
  - source /home/hicr/.hicr-env.sh
  - echo "Compiling OVNI..."
  - mkdir extern/tracr/extern/ovni/build; pushd extern/tracr/extern/ovni/build; cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTING=FALSE; make -j24; sudo make install; popd
  - echo "Building TaskR..."
  - mkdir build
  - meson setup build -Dbuildtype=debug -Db_coverage=true -DbuildTests=true -DbuildExamples=true -DdistributedEngine=mpi -DbuildInstrumentation=true -DcompileWarningsAsErrors=true
  - meson compile -C build
  - echo "Running tests..."
  - meson test -C build
  - echo "Creating coverage report..."
  - ninja -C build coverage
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    when: always
    paths:
      - build/meson-logs/*
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/meson-logs/coverage.xml 
  only:
  - main
  - merge_requests
  - tags