build:
  image: ghcr.io/algebraic-programming/taskr/buildenv:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
  - docker
  - x86
  - infiniband 
  script:
  # Build Pybind11
  - sudo apt-get update
  - sudo apt-get install -y python3-pytest
  - /usr/bin/python3 -m pip install --upgrade pip pytest
  - cd extern/pybind11
  - mkdir -p build
  - cd build
  - cmake .. -DPython_EXECUTABLE=/usr/bin/python3
  - make check -j"$(nproc)"
  - mkdir -p mock_install/share/pkgconfig
  - |
    cat <<EOF > mock_install/share/pkgconfig/pybind11.pc
    prefix=$(pwd)/..
    includedir=\${prefix}/include

    Name: pybind11
    Description: Seamless operability between C++11 and Python
    Version: 2.13.6
    Cflags: -I\${includedir}
    EOF
  - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$(pwd)/mock_install/share/pkgconfig"

  # TaskR build process
  - cd ../../../..
  - export HOME=/home/hicr
  - source /home/hicr/.hicr-env.sh
  - echo "Building TaskR..."
  - mkdir build
  - meson setup build -Dbuildtype=debug -Db_coverage=true -DbuildTests=true -DbuildExamples=true -DdistributedEngine=mpi -DexecutionStateType=boost,nosv -DprocessingUnitType=pthreads,nosv -DbuildInstrumentation=true -DbuildPyTaskR=true -DcompileWarningsAsErrors=true
  - meson compile -C build
  - echo "Running tests..."
  - meson test -C build
  - echo "Creating coverage report..."
  - ninja -C build coverage
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    when: always
    paths:
      - build/meson-logs/*
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/meson-logs/coverage.xml 
  only:
  - main
  - tags
