name: Merge into master - Build and Run Tests

# if statements modified to avoid: https://stackoverflow.com/questions/69354003/github-action-job-fire-when-previous-job-skipped

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  DOCKERIMAGE: ghcr.io/algebraic-programming/taskr/buildenv

jobs:
  build-docker-amd64:
    uses: Algebraic-Programming/TaskR/.github/workflows/master-build-workflow.yml@main
    with:
      os: ubuntu-24.04
      arch: amd64
  
  push-buildenv-manifest:
    runs-on: ubuntu-latest
    needs: [ build-docker-amd64]
    if: |
      always() &&
      (contains(needs.build-docker-amd64.result, 'success'))
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest images
        run:
          docker buildx imagetools create --tag ${{ env.DOCKERIMAGE }}:latest ${{ env.DOCKERIMAGE }}:amd64-latest 

  compile-and-test-amd64:
    needs: [ push-buildenv-manifest ]
    if: |
      always() &&
      (contains(needs.push-buildenv-manifest.result, 'success') || contains(needs.push-buildenv-manifest.result, 'skipped'))
    uses: Algebraic-Programming/TaskR/.github/workflows/master-test-workflow.yml@main
    with:
      os: ubuntu-24.04
      arch: amd64


